GITHUB_HEX_DICT_CSV_URL = "https://raw.githubusercontent.com/xshobux/dqx_custom_translations/main/csv/hex_dict.csv"
GITHUB_CUSTOM_TRANSLATIONS_ZIP_URL = "https://github.com/xshobux/dqx_custom_translations/archive/refs/heads/main.zip"
GITHUB_CLARITY_VERSION_UPDATE_URL = "https://raw.githubusercontent.com/xshobux/dqxclarity/weblate/version.update"
GITHUB_CLARITY_MERGE_XLSX_URL = "https://raw.githubusercontent.com/xshobux/dqx_custom_translations/main/csv/merge.xlsx"
GITHUB_WEBLATE_ZIP_URL = "https://github.com/dqxtranslationproject/dqx_translations/archive/refs/heads/main.zip"
