repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
    name: Check for newline at end of file
  - id: no-commit-to-branch
    name: Ensure we don't push to main
    args: [--branch, main]
  - id: fix-byte-order-marker
    name: Remove UTF-8 byte order marker (BOM)
  - id: mixed-line-ending
    name: Fix line endings
    args: ['--fix', 'crlf']
  - id: trailing-whitespace
    name: Check for trailing whitespace
  - id: check-merge-conflict
    name: Check for merge conflicts
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    name: Checking for potential passwords
