namespace DqxClarity.Launcher.Services;

public static class Send2ChatStrings
{
    public static readonly IReadOnlyDictionary<string, string> Quests = new Dictionary<string, string>
    {
        { "Asfeld: Chapter 5", "わかめ かめかめ うみのさち" },
        { "Asfeld: Place of Prayer", "オープンザチャクラ" },
        { "Q485: Dark King Slime Unlock", "りゅうとうしがあらわれた！コマンド？" },
        { "Quest 001", "みーつけた！" },
        { "Quest 002", "ごめんねなの！" },
        { "Quest 003", "せんせいおしえて！" },
        { "Quest 004", "ごはんだよ！" },
        { "Quest 005", "おめでとーん！" },
        { "Quest 175", "私はマイスターです。何かお困りですか？" },
        { "Quest 331", "ベジーク・ベジセルク！" },
        { "Quest 392", "ラナルータ" },
        { "Quest 421", "われ かのちをめざす" },
        { "Quest 422", "ラナルータ" },
        { "Quest 450", "ナドラガンドにヒカリあれ" },
        { "Quest 453", "マイユさーん！" },
        { "Quest 480", "モモンタル" },
        { "Quest 496", "るるるんぽう" },
        { "Quest 505 (1)", "おおきくなあれ！タネタネきゅん！" },
        { "Quest 505 (2)", "てんまでとどけ！タネきゅんきゅん" },
        { "Quest 516", "サインください" },
        { "Quest 531", "ようせいさん ようせいさん" },
        { "Quest 538", "フミンフキュウ" },
        { "Quest 561", "イア・タア・シンパッ・ケウ" },
        { "Quest 578", "われらみなレトリウスのこ" },
        { "Quest 580", "ギリウスへいか ばんざい" },
        { "Quest 581", "おくすりのじかんです" },
        { "Quest 606", "ベントラー" },
        { "Quest 608", "デスマスターはしなない" },
        { "Quest 616", "げいじゅつはマデッサンスなり" },
        { "Quest 627", "ガッタバ・ヨナクーン" },
        { "Quest 660", "まじんのもんよひらけ" },
        { "Quest 672", "ことばトハ いしナリ" },
        { "Quest 709", "てんそうしがらん" },
        { "Quest 728", "げんえいのほろ" },
        { "Quest 761", "うんめいとは" },
        { "Quest 833", "おなかいっぱい" },
        { "Quest 839", "オオカミがでたぞー！" },
        { "Quest 844", "スエル" },
        { "Seasonal: Christmas Phrase", "メリークリスマス" },
        { "Seasonal: Halloween Phrase", "トリックオアトリート" },
        { "Seasonal: Star Festival", "だいすき" },
        { "Seasonal: Valentine's Phrase", "ハッピーバレンタイン" },
        { "Seasonal: White Day Phrase", "ハッピーホワイトデー" },
        { "Seasonal: White Day 2026 Quest", "うけとってください" },
        { "Version 3.2", "おままごとしましょー" },
        { "Version 3.3 (1)", "にんげん" },
        { "Version 3.3 (2)", "われワギにちかう" },
        { "Version 3.4 Sea of Worth", "みのり" },
        { "Version 3.4 Sea of Unity", "やすらぎ" },
        { "Version 3.4 Sea of Peace", "しあわせ" },
        { "Version 3.4 Sea of Doubt", "ためらい" },
        { "Version 3.4 Sea of Sleep", "えいえん" },
        { "Version 3.4 Sea of Light", "よろこび" },
        { "Version 4.0: Dancer 1 (Nina)", "ニイナ" },
        { "Version 4.0: Dancer 2 (Cute)", "キュート" },
        { "Version 4.0: Dancer 3 (Rominique)", "ロミニク" },
        { "Version 4.4 (1)", "よろこびのそのであおう" },
        { "Version 4.4 (2)", "フォステイルが！" },
        { "Version 4.5", "ユマテルのカギ" },
        { "Version 5.2 (1)", "リドよめざめよ" },
        { "Version 5.2 (2)", "われじゆうをもとむ" },
        { "Version 5.5", "リドよわがともよ" },
        { "Version 6.1", "むすすへえまめともりかひしうとんさられわ" },
        { "Version 6.5", "こうろのかぎ" },
        { "Version 7.0", "まれびと" },
        { "Version 7.1 (1)", "ニワトリ" },
        { "Version 7.1 (2)", "ネズミ" },
        { "Version 7.2", "だんざいのけん！" },
        { "Version 7.5", "むにえかのまち" },
    };

    public static readonly IReadOnlyDictionary<string, string> CommonPhrases = new Dictionary<string, string>
    {
        { "Thank you!", "ありがとう！" },
        { "Hello!", "こんにちは！" },
        { "Good luck!", "がんばって！" },
        { "Congrats!", "おめでとう！" },
        { "No problem.", "どういたしまして" },
        { "Nice to meet you.", "よろしくお願いします" },
        { "Nice job, everyone!", "おつかれさまでした" },
        { "Sorry.", "ごめんなさい" },
        { "Are you ready?", "準備ＯＫ？" },
        { "I'll do my best!", "がんばります！" },
        { "I understand.", "わかりました" },
    };
}
