---
name: "prod-release"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  prod-release:
    if: startsWith(github.event.pull_request.title, 'release')
    name: "Prod release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clone dqx-translation-project/dqx_translations
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: "dqx-translation-project"
          repository: "dqx_translations"
      - name: Read version.update file
        uses: juliangruber/read-file-action@v1
        id: template
        with:
          path: ./version.update
      - name: Increment version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.template.outputs.content }}
          version-fragment: "feature"
      - name: Write new version to file
        uses: DamianReeves/write-file-action@master
        with:
          path: ./version.update
          contents: ${{ steps.bump_version.outputs.next-version }}
          write-mode: "overwrite"
      - name: Clone dqx-translation-project/dqx-custom-translations
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: "dqx-translation-project"
          repository: "dqx-custom-translations"
      - name: Build dev package
        run: |
          rsync -av --exclude="imgs/" app/* dqxclarity/;
          cp version.update requirements.txt user_settings.ini dqxclarity/;
          cp -fr dqx-custom-translations/json/* dqxclarity/misc_files;
          cp -f dqx-custom-translations/csv/glossary.csv dqxclarity/misc_files;
          cp -f dqx_translations/json/_lang/en/eventTextSysQuestaClient.json dqxclarity/misc_files;
          cp -f dqx_translations/json/_lang/en/subPackage05Client.json dqxclarity/misc_files;
          cp -f dqx_translations/json/_lang/en/subPackage41Client.win32.json dqxclarity/misc_files;
          cp -f dqx_translations/json/_lang/en/subPackage02Client.win32.json dqxclarity/misc_files;
          cp -f dqx_translations/json/_lang/en/smldt_msg_pkg_NPC_DB.win32.json dqxclarity/misc_files;
          zip -r dqxclarity.zip dqxclarity
          rm -rf dqx_translations;
          rm -rf dqx-custom-translations;
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update version to ${{ steps.bump_version.outputs.next-version }}." -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
      - name: Creating prod release
        uses: softprops/action-gh-release@v1
        with:
          files: dqxclarity.zip
          prerelease: false
          draft: false
          tag_name: v${{ steps.bump_version.outputs.next-version }}
          name: "Release: v${{ steps.bump_version.outputs.next-version }}"
          generate_release_notes: true
      - name: Open Pull Request
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: "main"
          TO_BRANCH: "dev"
          PULL_REQUEST_TITLE: "Sync: main to dev"
          PULL_REQUEST_BODY: "sync-branches: Moving code from main back to dev."
